### ISSUE TITLE
[Query] change json filter doesn't update advanced search

### ISSUE THREAD

**Issue by berthieresteban** [kuzzleio/kuzzle-admin-console#742]
Add a query using advanced filter `age equal 24`.
Change the query using raw json filter `age equal 42`.
Advanced filter still to `age equal 24` but the current applyed query is `age equal 42`.

**Comment by xbill82** [comment]
We are not going to implement the bi-directional filter sync, but we're going to try to improve the UX, in order to make it more explicit for the user that the Raw filter is generated from the Advanced filter.

* We're adding a "Generate Raw" button in the "Advanced Filter" tab. Clicking it automatically switches to the Raw filter tab.
* We're changing the labels of the search buttons to "Quick Search", "Advanced Search" and "Raw Search" (each button will only trigger the query from the corresponding tab).
* Triggering an Advanced Search will no more synchronize the query to the Raw filter tab.
