### ISSUE TITLE
Textarea for editing document is too short and mapping is automatically unfolded

### ISSUE THREAD

**Issue by Tyki** [kuzzleio/kuzzle-admin-console#774]
Being able to edit more than 15 rows of content

## Current Behavior

Small textarea and veryyy long page with the mapping

## Possible Solution

Let the mapping folded and unfoldable + let the user adjust (and save  the setting?) the textarea if possible

## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment)

Kuzzle version:
Node.js version:
Admin Console Version:

**Comment by Njuelle** [comment]
We are working on some improvements to allow for a more convenient editing area

**Comment by Tyki** [comment]
There was screens in the ticket ..

![screencapture-next-console-kuzzle-io-2020-07-01-09_29_36](https://user-images.githubusercontent.com/2605688/86215853-68b1a480-bb7d-11ea-9d10-968d2e49c05b.png)

**Comment by Aschen** [comment]
The mappings should be folded by default IMHO

**Comment by Tyki** [comment]
@Njuelle you said that you are working on improvements, it means that's it's under progress or it's planned? I can maybe try to fix on my own and submit a PR to you guys ?

@xbill82 what do you think?

**Comment by Njuelle** [comment]
O_0 Damn :scream: ! We've never tested with a mapping this big before. You're right, we need to fold the mapping tree-view by default !
@Tyki , For the moment it's only planned and we're only at the reflective phase. We are thinking of having the possibility to have the JSON textarea in full screen mode. BTW feel free to submit a PR to fix the loooooong unfolded mapping ! And above all, thanks you for this precious feedback :)

**Comment by xbill82** [comment]
@Tyki it's a shame, we should rewrite everything in Javascript. Oh, wait...
Jokes apart, the current JSON formatter is a very old and dusty thing we want to get rid of, but this doesn't seem to me like a problem related to the component itself rather than the global page layout.
In fact, IMHO, the mapping hint should be contained into a scrollable `div` whose height is defined by the space available from the bottom of the breadcrumbs to the bottom of the screen. We need to rework the layout of the page so that the whole component is Flexbox-ed and able to compute dynamically the available space.

And, indeed, thanks for the invaluable feedback!
