### ISSUE TITLE
Add the possibility to delete the first condition in advanced search

### ISSUE THREAD

**Issue by Njuelle** [kuzzleio/kuzzle-admin-console#909]
## Expected Behavior
Add the possibility to delete the first condition in advanced search and keep the others ones to avoid having to do a complete reset of the filters.

## Context (Environment)
Kuzzle version: 1, 2
Admin Console version: 4.x

**Comment by xbill82** [comment]
i have fixed this issue when rewriting the advanced filter for the Alerts section of Kuzzle IoT Platform. This complete rewrite solves many more issues but will be ported to the AC in a very long time. The best thing to do is to take a look at the code of the new version of the component and just apply it here (not linking it here since the repo is private).
